export const SET_CART_DATA = "SETCARTDATA";
export const SIGN_IN_USER = "SIGNINUSER";
export const SET_CART_NUM = "SETCARTNUM";
export const SET_COMPLETED_CART = "SETCOMPLETEDCART";
export const SET_SALES_TEAM_DATA = "SETSALESTEAMDATA";
export const SET_IS_SAFARI = "SETISSAFARI";
